### ISSUE TITLE
Question: Why do you use URI instead of Mojo::URL

### ISSUE THREAD

**Issue by kberov** [Grinnz/Mojo-SQLite#4]
Isn't Mojo::URL capable to parse the accepted convention for database connection in Mojo::AnyDatabaseHere world?

**Comment by Grinnz** [comment]
URI is used because of URI::file's capability to translate local filesystem paths (such as from Windows and OS/2) into URL format; Mojo::URL does not implement all of these system-specific formats and I wouldn't expect it to. URI has no dependencies which is a bonus. I used URI in the rest of the dist (such as parsing and forming the connection URI) to be consistent.

**Comment by kberov** [comment]
Thanks! And thanks for implementing this module too!
